/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrideBillComparator;

import java.io.File;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HAGRAWA
 */
public class AmdocsEEPdfBillComparatorl extends javax.swing.JFrame {

    /**
     * Creates new form BrideBill
     */
    public AmdocsEEPdfBillComparatorl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ExportResulttoExcel = new javax.swing.JButton();
        ChooseBBBillDir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ChooseEEBillDir = new javax.swing.JButton();
        EEBillDirectory = new javax.swing.JLabel();
        BriteBillDirectory = new javax.swing.JLabel();
        StartComparison = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultTable = new javax.swing.JTable();
        Heading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" PDF Comparator");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("EE Bill Directory");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 159, 196, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Results");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        ExportResulttoExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ExportResulttoExcel.setText("<html><center> Export Results <br> to Excel");
        ExportResulttoExcel.setEnabled(false);
        ExportResulttoExcel.setPreferredSize(new java.awt.Dimension(337, 227));
        ExportResulttoExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportResulttoExcelActionPerformed(evt);
            }
        });
        getContentPane().add(ExportResulttoExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 208, 151, 41));

        ChooseBBBillDir.setText("<html>Choose Brite Bill Directory");
        ChooseBBBillDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseBBBillDirActionPerformed(evt);
            }
        });
        getContentPane().add(ChooseBBBillDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 84, 295, 45));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Brite Bill Directory");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 159, 258, 20));

        ChooseEEBillDir.setText("<html>Choose EE Bill Directory ");
        ChooseEEBillDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseEEBillDirActionPerformed(evt);
            }
        });
        getContentPane().add(ChooseEEBillDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 84, 252, 45));
        getContentPane().add(EEBillDirectory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 438, 25));
        getContentPane().add(BriteBillDirectory, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 210, 336, 25));

        StartComparison.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StartComparison.setText("Start comparison");
        StartComparison.setEnabled(false);
        StartComparison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartComparisonActionPerformed(evt);
            }
        });
        getContentPane().add(StartComparison, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 84, -1, 35));

        ResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.no", "Bill Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ResultTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(ResultTable);
        ResultTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 1050, -1));

        Heading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Heading.setText("Amdocs/EE-BT PDF Comparator");
        getContentPane().add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChooseBBBillDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseBBBillDirActionPerformed
        // TODO add your handling code here:
        BriteBillDirectory.setText((new FileOperations()).getDirectory());
        enableButtons();
    }//GEN-LAST:event_ChooseBBBillDirActionPerformed

    private void ChooseEEBillDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseEEBillDirActionPerformed
        // TODO add your handling code here:
        EEBillDirectory.setText((new FileOperations()).getDirectory());
        enableButtons();        
    }//GEN-LAST:event_ChooseEEBillDirActionPerformed

    private void ExportResulttoExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportResulttoExcelActionPerformed
        // TODO add your handling code here:
        ExcelExport.createExcel(ResultTable);
    }//GEN-LAST:event_ExportResulttoExcelActionPerformed

    private void StartComparisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartComparisonActionPerformed
        // TODO add your handling code here:
       ExportResulttoExcel.setEnabled(false);
        DefaultTableModel dm = (DefaultTableModel) ResultTable.getModel();
        for (int i = ResultTable.getRowCount()- 1; i >= 0; i--) {
            dm.removeRow(i);
        }   
        
        File eEDir = new File(EEBillDirectory.getText());
        File bBDir = new File(BriteBillDirectory.getText());
    
        ResultTable = Formatter.createTable(eEDir, bBDir,ResultTable);        
        enableButtons();        

    }//GEN-LAST:event_StartComparisonActionPerformed

    private void enableButtons(){
        if (ResultTable.getRowCount() > 0) {
            ExportResulttoExcel.setEnabled(true);
        }
        else
            ExportResulttoExcel.setEnabled(false);
        
        if (!EEBillDirectory.getText().isEmpty() && !BriteBillDirectory.getText().isEmpty()) {
            StartComparison.setEnabled(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AmdocsEEPdfBillComparatorl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AmdocsEEPdfBillComparatorl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AmdocsEEPdfBillComparatorl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AmdocsEEPdfBillComparatorl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AmdocsEEPdfBillComparatorl().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BriteBillDirectory;
    private javax.swing.JButton ChooseBBBillDir;
    private javax.swing.JButton ChooseEEBillDir;
    private javax.swing.JLabel EEBillDirectory;
    private javax.swing.JButton ExportResulttoExcel;
    private javax.swing.JLabel Heading;
    private javax.swing.JTable ResultTable;
    private javax.swing.JButton StartComparison;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
