/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrideBillComparator;

import javax.swing.JFileChooser;

/**
 *
 * @author HAGRAWA
 */
public class AmdocsEEPdfBillComparatorl extends javax.swing.JFrame {

    /**
     * Creates new form BrideBill
     */
    public AmdocsEEPdfBillComparatorl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ExportResulttoExcel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        EEBillDirectory = new javax.swing.JLabel();
        BriteBillDirectory = new javax.swing.JLabel();
        StartComparison = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Amdocs/ EE PDF Bill Comparator");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("EE Bill Directory");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 159, 196, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "S.no", "Bill Name", "Failure reason"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 1037, 76));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Results");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        ExportResulttoExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ExportResulttoExcel.setText("<html><center> Export Results <br> to Excel");
        ExportResulttoExcel.setEnabled(false);
        ExportResulttoExcel.setPreferredSize(new java.awt.Dimension(337, 227));
        ExportResulttoExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportResulttoExcelActionPerformed(evt);
            }
        });
        getContentPane().add(ExportResulttoExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 208, 151, 41));

        jButton2.setText("<html>Choose Brite Bill Directory");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 84, 295, 45));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Brite Bill Directory");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 159, 258, 20));

        jButton3.setText("<html>Choose EE Bill Directory ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 84, 252, 45));
        getContentPane().add(EEBillDirectory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 438, 25));
        getContentPane().add(BriteBillDirectory, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 210, 336, 25));

        StartComparison.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StartComparison.setText("Start comparison");
        StartComparison.setEnabled(false);
        StartComparison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartComparisonActionPerformed(evt);
            }
        });
        getContentPane().add(StartComparison, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 84, -1, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     JFileChooser chooser = new JFileChooser(); 
    chooser.setCurrentDirectory(new java.io.File("."));
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    //
    // disable the "All files" option.
    //
    chooser.setAcceptAllFileFilterUsed(false);
    //    
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
      BriteBillDirectory.setVisible(true);
      BriteBillDirectory.setText(chooser.getCurrentDirectory().toString());
      
      }
    
    if(!EEBillDirectory.getText().isEmpty() && !BriteBillDirectory.getText().isEmpty()){
        StartComparison.setEnabled(true);
    }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       JFileChooser chooser = new JFileChooser(); 
    chooser.setCurrentDirectory(new java.io.File("."));
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    //
    // disable the "All files" option.
    //
    chooser.setAcceptAllFileFilterUsed(false);
    //    
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
      EEBillDirectory.setVisible(true);
      EEBillDirectory.setText(chooser.getCurrentDirectory().toString());
      
      }  
    
    if(!EEBillDirectory.getText().isEmpty() && !BriteBillDirectory.getText().isEmpty()){
        StartComparison.setEnabled(true);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ExportResulttoExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportResulttoExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExportResulttoExcelActionPerformed

    private void StartComparisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartComparisonActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_StartComparisonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AmdocsEEPdfBillComparatorl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AmdocsEEPdfBillComparatorl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AmdocsEEPdfBillComparatorl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AmdocsEEPdfBillComparatorl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AmdocsEEPdfBillComparatorl().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BriteBillDirectory;
    private javax.swing.JLabel EEBillDirectory;
    private javax.swing.JButton ExportResulttoExcel;
    private javax.swing.JButton StartComparison;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
